spring.application.name=game-studio-korea

spring.datasource.url=jdbc:mysql://localhost:3306/game_studio_korea
spring.datasource.username=gsk_portfolio
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true